spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082

keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: university
  resource: spring-client
  public-client: true

eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/